# Generated by Django 3.0.6 on 2020-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
